[project]
name = "motor-driver-test"
version = "0.1.0"
description = "TB6612FNG motor driver control for Raspberry Pi robot"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fake-rpi>=0.7.1",
    "numpy>=2.3.2",
    "rpi-gpio>=0.7.1",
]
